Ped Model Id (Intellisense)
mta-slipe/Slipe-Server pull request #130
Opened 2021-02-21 23:41 UTC by LukeSeers

Thanks @8BallBomBom for creating a script that takes given data and converts it to enum 👍 

I've added all the Ped model ID's with the given names.
![image](https://user-images.githubusercontent.com/16389426/108641948-8b912000-74a2-11eb-88b2-b55663fdde5d.png)

2021-02-21 23:43 UTC, LukeSeers commented on .gitignore
> +.idea/
I wasn't sure if to leave it in, but I thought eh might as well.

2021-02-22 21:47 UTC, NanoBob requested changes

2021-02-22 21:47 UTC, NanoBob commented on .gitignore
> +.idea/
That's perfectly fine

2021-02-22 21:47 UTC, NanoBob commented on SlipeServer.Server/Elements/Enums/PedModel.cs
> +        Wmymech = 50,
I would rather have this in numerical order (ascending) like most enums.

2021-02-23 08:32 UTC, NanoBob approved these changes

2021-02-23 08:32 UTC, merged