Adding voice behaviour
mta-slipe/Slipe-Server pull request #137
Opened 2021-08-04 16:46 UTC by ERAGON007

I made some changes in the repo, but not completed yet they need to be reviewed

2021-08-05 09:17 UTC, NanoBob commented on SlipeServer.Packets/Definitions/Voice/VoiceDataPacket.cs
> +            // Write the source player id
These comments can be removed, the code is self explanatory enough

2021-08-05 09:17 UTC, NanoBob commented on SlipeServer.Server/Behaviour/VoiceBehaviour.cs
> +                    server.BroadcastPacket(packet);
Broadcasting also sends the packet to the client it originated from, is that desired?

2021-08-05 09:17 UTC, NanoBob commented on SlipeServer.Server/Configuration.cs
> +        public bool IsVoiceEnabled { get; set; } = true;
Personally I think voice should default to being disabled

2021-08-05 09:17 UTC, NanoBob commented on SlipeServer.Server/Elements/Player.cs
> +        public bool IsMuted { get; set; }
Players can also be muted for chat purposes, so I would rename this to:
`IsVoiceMuted` (and later add a `IsChatMuted`)

2021-08-08 08:49 UTC, ERAGON007 commented
Fixed conflicts with #138 and done implementing of voice support (needs further testing with 2 clients connected) before merge

2021-08-08 09:32 UTC, NanoBob requested changes

2021-08-08 09:32 UTC, NanoBob commented on SlipeServer.Server/Elements/Player.cs
> +            this.OnVoiceData?.Invoke(this, new PlayerVoiceStartArgs(this, voiceData));
The only suggestion I would still add for this PR is using `IsVoiceMuted`, and only triggering the `OnVoiceData` event if the user is not muted.

2021-08-08 10:35 UTC, NanoBob approved these changes

2021-08-08 10:49 UTC, merged