Implement Ped Sync
mta-slipe/Slipe-Server pull request #171
Opened 2021-08-19 09:07 UTC by ERAGON007

Defined related packets in #90

2021-08-19 09:28 UTC, Zangomangu commented on SlipeServer.Packets/Definitions/Ped/PedSyncPacket.cs
> +        public override PacketReliability Reliability { get; } = PacketReliability.ReliableSequenced;
Ped sync packet should not be sent reliably, only sequenced. It is sent continously and should be able to drop packets, but they should arrive in the right order (sequenced)

```suggestion
        public override PacketReliability Reliability { get; } = PacketReliability.UnreliableSequenced;
```

2021-08-19 09:47 UTC, Zangomangu commented on SlipeServer.Packets/Definitions/Ped/PedSyncPacket.cs
> +                data.Model = reader.GetByte();
I don't think the Element ID is contained in just 1 byte?
Afaik it's uint so 2 bytes (you also defined it as uint in SyncData :))

```suggestion
                data.Model = reader.GetUint16();
```

2021-08-19 09:50 UTC, Zangomangu commented on SlipeServer.Packets/Definitions/Ped/PedSyncPacket.cs
> +                    data.Rotation = reader.GetByte();
Rotation can't be 1 byte, must be a float?

```suggestion
                    data.Rotation = reader.GetFloat();
```

2021-08-19 09:51 UTC, Zangomangu commented on SlipeServer.Packets/Definitions/Ped/PedSyncPacket.cs
> +                    data.Health = reader.GetByte();
Same as above

2021-08-19 09:51 UTC, Zangomangu commented on SlipeServer.Packets/Definitions/Ped/PedSyncPacket.cs
> +                    data.Armor = reader.GetByte();
Same as above

2021-08-19 13:43 UTC, Zangomangu commented on SlipeServer.Packets/Definitions/Ped/PedStartSyncPacket.cs
> +            SourceElementId = sourceElementId;
Now that you used PedElementId in the other packet, I think the same one should be used in all of these packets
So either SourceElementId or PedElementId

2021-08-19 13:44 UTC, Zangomangu commented on SlipeServer.Packets/Definitions/Ped/PedStartSyncPacket.cs
> +        public PedStartSyncPacket()
Necessary?

2021-08-19 17:27 UTC, ERAGON007 commented on SlipeServer.Packets/Definitions/Ped/PedStartSyncPacket.cs
> +        public PedStartSyncPacket()
yes, some packets need an empty constructor

2021-08-20 08:02 UTC, Zangomangu approved these changes
Only comment is about the variable name above 👍

2021-08-20 08:22 UTC, ERAGON007 commented on SlipeServer.Packets/Definitions/Ped/PedStartSyncPacket.cs
> +            SourceElementId = sourceElementId;
Will do in next commit

2021-08-20 08:39 UTC, ERAGON007 commented
Just gonna need some help with part of HitDetection

2021-08-20 18:51 UTC, NanoBob requested changes

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Packets/Definitions/Ped/PedStartSyncPacket.cs
> +            Position = position;
Prefix these with `this.`, so you get `this.Position = position`.
If you go to the error list window in Visual Studio and enable messages it will show you messages for these style issues.

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Packets/Definitions/Ped/PedStartSyncPacket.cs
> +            builder.Write(Position.X);
Same here, also use `this.`

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Packets/Definitions/Ped/PedSyncPacket.cs
> +        public struct SyncData
Move the struct to a separate file, and rename it to `PedSyncData`

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Packets/Definitions/Ped/PedSyncPacket.cs
> +                    // Vehicle ID
These comments aren't necesary

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Packets/Definitions/Ped/PedSyncPacket.cs
> +                    // Position
You could create a flags enum for this with the values `0x01`, `0x02` etc. And name them appropriately, then use those instead of the number here.
```cs
enum PedSyncFlags
{
    Position = 0x01,
    Rotation = 0x02,
    Velocity = 0x04,
   // etc
}

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Packets/Definitions/Ped/PedTaskPacket.cs
> +            DataBuffer = new bool[56];
`this.`

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Packets/Definitions/Ped/PedTaskPacket.cs
> +        public override byte[] Write()
Wasn't this the packet where we noticed it was actually defined?

Quote from Discord
> So for reading the packet on the server:
> ```
> - ushort taskType
> - ElementId attackerId
> - byte hitBodyPart
> - byte hitBodySize
> - byte weaponId
> ```

> And for sending it to the client:
> ```
> - ElementId sourcePlayer
> - ushort taskType
> - ElementId attackerId
> - byte hitBodyPart
> - byte hitBodySize
> - byte weaponId
> ```
> (Same but with the element ID before it)

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Server/Extensions/Vector3Extensions.cs
> +    public static class Vector3Extensions
These aren't neccesary, these methods are already available as:
```cs
System.Numerics.Vector3.Distance
System.Numerics.Vector2.Distance
```
And you can then just compare those values. So this file can be removed as a whole.

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Server/PacketHandling/QueueHandlers/PedSyncQueueHandler.cs
> +                            // TODO: use DoHitDetection here
Hit detection is not neccesary here as it is already sorted by `CollisionShapeBehaviour`

2021-08-20 18:51 UTC, NanoBob commented on SlipeServer.Server/PacketHandling/QueueHandlers/PedSyncQueueHandler.cs
> +                            pedElement.Position = syncData.Position;
Put all these updates in a `.RunAsSync` block, check the syncqueuehandler for how this is done with puresync as an example.

2021-08-22 20:17 UTC, NanoBob requested changes

2021-08-22 20:17 UTC, NanoBob commented on SlipeServer.Server/Elements/Element.cs
> +        public IEnumerable<CollisionShape> Collisions { get; set; }
Is this used? If not, can be removed.

2021-08-22 20:17 UTC, NanoBob commented on SlipeServer.Server/Elements/Ped.cs
> +        public bool IsOnFire { get; set; }
Remove these properties from the `Player` class since they are now on `Ped`

2021-08-22 20:17 UTC, NanoBob commented on SlipeServer.Server/PacketHandling/QueueHandlers/PedSyncQueueHandler.cs
> +                        // Stop syncer from syncing it
Remove these comments, the method names are already clear enough.

2021-08-22 20:17 UTC, NanoBob commented on SlipeServer.Server/PacketHandling/QueueHandlers/PedSyncQueueHandler.cs
> +            var allPlayers = this._elementRepository.GetByType<Player>(ElementType.Player)
Instead of `GetByType` use `GetWithinRange<Player>`. It's a much more efficient way of getting players close to a certain position. So it won't need to loop through all players but only through those close by.

2021-08-22 20:17 UTC, NanoBob commented on SlipeServer.Server/PacketHandling/QueueHandlers/PedSyncQueueHandler.cs
> +                    // Is the player syncing this ped?
No need for these comments

2021-08-22 20:17 UTC, NanoBob commented on SlipeServer.Server/PacketHandling/QueueHandlers/PedSyncQueueHandler.cs
> +                            // Send this sync
These comments are also not neccesary

2021-08-22 20:17 UTC, NanoBob commented on SlipeServer.Server/PacketHandling/QueueHandlers/PedSyncQueueHandler.cs
> +                // Tell the player
No need for these comments

2021-08-22 20:17 UTC, NanoBob commented on SlipeServer.Server/Elements/Player.cs
> +        public List<Ped> SyncingPeds { get; set; }
We want to make sure if a ped is destroyed it's no longer being sync'd by any player

2021-08-23 16:00 UTC, ERAGON007 commented on SlipeServer.Server/Elements/Player.cs
> +        public List<Ped> SyncingPeds { get; set; }
i think new commit covers this issue

2021-08-23 20:37 UTC, NanoBob requested changes

2021-08-23 20:37 UTC, NanoBob commented on SlipeServer.Server/Behaviour/TeamBehaviour.cs
> +                        TeamId = args.NewTeam!.Id
What if the player has been removed from its team?

2021-11-02 22:08 UTC, NanoBob approved these changes

2021-11-02 22:11 UTC, merged