PlayerNetworkStatusPacket
mta-slipe/Slipe-Server pull request #180
Opened 2021-08-21 07:05 UTC by CrosRoad95

I don't know how to test it on local server

2021-08-21 08:19 UTC, NanoBob requested changes
Do make sure you test it, either ask someone else to connect to your server or use a VM for testing

2021-08-21 08:19 UTC, NanoBob commented on SlipeServer.Packets/Definitions/Player/PlayerNetworkStatusPacket.cs
> +                    this.Type = PlayerNetworkStatusType.InterruptionBegan;
You don't need this switch case, you can just cast the byte to `PlayerNetworkStatusType`

2021-08-22 05:42 UTC, CrosRoad95 commented
To test it on local server, you need to attach debugger to gta_sa.exe and pause process, you will notice messages appearing on server. When unpaused you will see how long client was hang
![image](https://user-images.githubusercontent.com/22455534/130343891-8ae06389-9cff-42cc-a433-3eb184b87e45.png)

2021-08-22 09:30 UTC, NanoBob approved these changes

2021-08-22 09:30 UTC, merged

2021-09-02 11:15 UTC, th1302 commented
Can you relpy my isssues