Feature - Host builder
mta-slipe/Slipe-Server pull request #515
Opened 2024-05-04 09:54 UTC by CrosRoad95

2024-05-07 15:43 UTC, NanoBob requested changes

2024-05-07 15:43 UTC, NanoBob commented on SlipeServer.Server/Services/ChatBox.cs
> +        this.root = server.RootElement;
Any particular reason for this change?

2024-05-07 15:43 UTC, NanoBob commented on SlipeServer.Server/Resources/Serving/BasicHttpServer.cs
> +        var configuration = mtaServer.Configuration;
Any particular reason for this change?

2024-05-07 15:43 UTC, NanoBob commented on SlipeServer.Server/Configuration.cs
> +    public ushort HttpPort { get; set; } = 22005;
Please exclude this change from the PR

2024-05-10 12:48 UTC, CrosRoad95 commented on SlipeServer.Server/Services/ChatBox.cs
> +        this.root = server.RootElement;
Yes, for future multi-mta servers models so it take root element of particular server, not some global one ( it should be done everywhere )

2024-05-10 12:49 UTC, CrosRoad95 commented on SlipeServer.Server/Resources/Serving/BasicHttpServer.cs
> +        var configuration = mtaServer.Configuration;
The same reason as above: grab configuration from particular mta server, but probably in this case wise would be to allow one http server serve files from multiple mta servers

2024-05-12 21:28 UTC, NanoBob approved these changes

2024-05-12 21:28 UTC, merged