Move controllers to example project
mta-slipe/Slipe-Server pull request #562
Opened 2024-10-29 20:11 UTC by CrosRoad95

2024-11-01 19:27 UTC, NanoBob requested changes

2024-11-01 19:27 UTC, NanoBob commented on SlipeServer.Example/Controllers/SingletonTestController.cs
> +        this.testService = this.serviceProvider.GetRequiredService<TestService>();
Why was this changed from constructor injection?

2024-11-03 12:27 UTC, CrosRoad95 commented on SlipeServer.Example/Controllers/SingletonTestController.cs
> +        this.testService = this.serviceProvider.GetRequiredService<TestService>();
Because it been and is Scoped service

2024-12-02 22:20 UTC, NanoBob approved these changes

2025-01-14 05:39 UTC, merged